server:
  port: 9090


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/javaEEtext?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true

mybatis:
  # ????????????? XML ???????
  # classpath: ??? resources ??????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.javaee.entity