server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xhsf?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 3166606294@qq.com
    password: wxjfulrtlrxkddbj
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器地址
    host: 127.0.0.1
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password: ""
    # 连接超时时间（毫秒，0 表示无超时）
    timeout: 0
    # Jedis 连接池配置
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 20
        # 连接池最大阻塞等待时间（负值表示无限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
# MyBatis-Plus 配置
mybatis-plus:
  # 核心配置（configuration 层级）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
    map-underscore-to-camel-case: true # 下划线转驼峰（属于configuration层级）
  # Mapper XML文件路径（根层级）
  mapper-locations: classpath:mapper/*.xml
  # 全局配置（根层级）
  global-config:
    db-config:
      logic-delete-field: deleteFlag  # 逻辑删除字段名（驼峰对应数据库del_flag）
      logic-delete-value: 1        # 已删除标记值
      logic-not-delete-value: 0    # 未删除标记值